import { getLanguageName } from '../../utils/language-names.ts';
import { parseTimeToSeconds } from '../../utils/time.ts';

export interface TranscriptSegment {
  start: number;
  duration: number;
  text: string;
}

export interface TranscriptResult {
  language: {
    code: string;
    name: string;
  };
  available_languages: Array<{
    code: string;
    name: string;
  }>;
  duration?: number;
  transcript: TranscriptSegment[];
}

export class TranscriptService {
  /**
   * Fetches the video transcript for a given video ID and optional language.
   */
  async getTranscript(videoId: string, lang?: string): Promise<TranscriptResult> {
    try {
      const primaryResult = await this.fetchPrimaryTranscript(videoId, lang);
      if (primaryResult && primaryResult.transcript.length > 0) {
        return primaryResult;
      }
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : '';
      if (msg.includes('No transcript is available')) {
        throw err;
      }
      // If primary failed with network error, try fallback
    }

    // Try fallback via Invidious public instances
    try {
      const fallbackResult = await this.fetchInvidiousTranscript(videoId, lang);
      if (fallbackResult && fallbackResult.transcript.length > 0) {
        return fallbackResult;
      }
    } catch {
      // Fallback also failed
    }

    throw new Error('No transcript is available for this video.');
  }

  /**
   * Primary transcript fetcher
   */
  private async fetchPrimaryTranscript(
    videoId: string,
    lang?: string
  ): Promise<TranscriptResult | null> {
    let url = `https://youtube-transcript.ai/transcript/${videoId}.txt`;
    if (lang && lang.trim().length > 0) {
      url += `?lang=${encodeURIComponent(lang.trim())}`;
    }

    const res = await fetch(url, {
      signal: AbortSignal.timeout(10000),
      headers: {
        'User-Agent':
          'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        Accept: 'text/plain, */*',
      },
    });

    if (res.status === 404) {
      throw new Error('No transcript is available for this video.');
    }

    if (res.status === 429) {
      throw new Error('Too many requests. Please try again shortly.');
    }

    if (!res.ok) {
      throw new Error('Something went wrong while fetching the transcript. Try again.');
    }

    const rawText = await res.text();
    return this.parseRawTranscriptText(rawText, lang);
  }

  /**
   * Parses the text transcript format into structured segments and metadata.
   */
  private parseRawTranscriptText(
    rawText: string,
    requestedLang?: string
  ): TranscriptResult {
    const lines = rawText.split('\n');
    let inTranscript = false;
    const segments: TranscriptSegment[] = [];

    let currentCode = requestedLang || 'en';
    const availableLanguagesMap = new Map<string, { code: string; name: string }>();
    let totalDurationSeconds: number | undefined;

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i].trim();
      if (!line) continue;

      // Extract current language and duration from header
      if (line.startsWith('Language:')) {
        const langMatch = line.match(/Language:\s*([a-zA-Z0-9\-_]+)/i);
        if (langMatch) {
          currentCode = langMatch[1];
        }

        const durMatch = line.match(/Duration:\s*(\d+:\d+(?::\d+)?)/i);
        if (durMatch) {
          totalDurationSeconds = parseTimeToSeconds(durMatch[1]);
        }
      }

      // Extract other available languages
      if (line.startsWith('Other available languages:')) {
        const rest = line.replace('Other available languages:', '').trim();
        const parts = rest.split(',').map((p) => p.trim()).filter(Boolean);

        for (const p of parts) {
          // Format like: "a-en (en) [auto]" or "de-DE (de-DE)" or "ja (ja)" or "es (es)"
          const m = p.match(/^([^\s\(]+)(?:\s*\(([^)]+)\))?(?:\s*\[([^\]]+)\])?/);
          if (m) {
            const code = m[1];
            const baseCode = m[2] || code;
            const isAuto = p.toLowerCase().includes('[auto]');
            const readableName = getLanguageName(baseCode) + (isAuto ? ' (auto)' : '');

            availableLanguagesMap.set(code, {
              code,
              name: readableName,
            });
          }
        }
      }

      if (line.startsWith('## Transcript')) {
        inTranscript = true;
        continue;
      }

      if (line.startsWith('---Generated by') || line.startsWith('---')) {
        inTranscript = false;
        break;
      }

      if (inTranscript) {
        // Line may contain one or multiple timestamps like [0:10] text...
        const regex = /\[(\d+:\d+(?::\d+)?)\]\s*([^\[]+)/g;
        let match;
        let matched = false;

        while ((match = regex.exec(line)) !== null) {
          matched = true;
          const timeStr = match[1];
          const text = match[2].trim();
          const startSeconds = parseTimeToSeconds(timeStr);

          if (text) {
            segments.push({
              start: startSeconds,
              duration: 0,
              text,
            });
          }
        }

        // If line is continuation text without brackets
        if (!matched && segments.length > 0 && !line.startsWith('[')) {
          segments[segments.length - 1].text += ` ${line}`;
        }
      }
    }

    if (segments.length === 0) {
      throw new Error('No transcript is available for this video.');
    }

    // Ensure current language is also in available languages list
    const currentName = getLanguageName(currentCode);
    if (!availableLanguagesMap.has(currentCode)) {
      availableLanguagesMap.set(currentCode, {
        code: currentCode,
        name: currentName,
      });
    }

    // Calculate duration for each segment based on the subsequent segment's start time
    for (let i = 0; i < segments.length; i++) {
      if (i < segments.length - 1) {
        const diff = segments[i + 1].start - segments[i].start;
        segments[i].duration = Math.max(1, Math.round(diff * 10) / 10);
      } else {
        const remaining = totalDurationSeconds
          ? totalDurationSeconds - segments[i].start
          : 5;
        segments[i].duration = Math.max(2, Math.round(remaining * 10) / 10);
      }
    }

    const availableLanguages = Array.from(availableLanguagesMap.values());

    return {
      language: {
        code: currentCode,
        name: currentName,
      },
      available_languages: availableLanguages,
      duration: totalDurationSeconds,
      transcript: segments,
    };
  }

  /**
   * Fallback using Invidious captions endpoint
   */
  private async fetchInvidiousTranscript(
    videoId: string,
    lang?: string
  ): Promise<TranscriptResult | null> {
    const instances = [
      'https://inv.nadeko.net',
      'https://invidious.privacydev.net',
      'https://iv.ggtyler.dev',
      'https://yewtu.be',
    ];

    for (const inst of instances) {
      try {
        const captionsUrl = `${inst}/api/v1/captions/${videoId}`;
        const res = await fetch(captionsUrl, {
          signal: AbortSignal.timeout(4000),
        });
        if (!res.ok) continue;

        const data = await res.json();
        if (!data.captions || !Array.isArray(data.captions) || data.captions.length === 0) {
          continue;
        }

        // Find matching or default track
        let track = data.captions[0];
        if (lang) {
          const matchedTrack = data.captions.find(
            (c: { languageCode: string }) => c.languageCode === lang
          );
          if (matchedTrack) track = matchedTrack;
        }

        const subtitleUrl = `${inst}${track.url}`;
        const subRes = await fetch(subtitleUrl, { signal: AbortSignal.timeout(4000) });
        if (!subRes.ok) continue;

        const vttText = await subRes.text();
        const segments = this.parseVttText(vttText);

        if (segments.length > 0) {
          return {
            language: {
              code: track.languageCode || 'en',
              name: track.label || getLanguageName(track.languageCode || 'en'),
            },
            available_languages: data.captions.map((c: { languageCode: string; label: string }) => ({
              code: c.languageCode,
              name: c.label || getLanguageName(c.languageCode),
            })),
            transcript: segments,
          };
        }
      } catch {
        // try next instance
      }
    }

    return null;
  }

  /**
   * Parses WebVTT into transcript segments.
   */
  private parseVttText(vttText: string): TranscriptSegment[] {
    const lines = vttText.split(/\r?\n/);
    const segments: TranscriptSegment[] = [];

    let currentStart = 0;
    let currentDuration = 0;
    let currentText = '';

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i].trim();
      if (!line || line.startsWith('WEBVTT') || line.startsWith('NOTE')) continue;

      // Look for timestamp line: "00:00:10.500 --> 00:00:13.200"
      const match = line.match(
        /(\d{1,2}:)?(\d{2}):(\d{2})[.,](\d{3})\s*-->\s*(\d{1,2}:)?(\d{2}):(\d{2})[.,](\d{3})/
      );

      if (match) {
        if (currentText && currentDuration > 0) {
          segments.push({
            start: currentStart,
            duration: currentDuration,
            text: currentText.trim(),
          });
          currentText = '';
        }

        const startParts = line.split('-->')[0].trim().replace(',', '.');
        const endParts = line.split('-->')[1].trim().replace(',', '.');

        currentStart = parseTimeToSeconds(startParts);
        const endSeconds = parseTimeToSeconds(endParts);
        currentDuration = Math.max(1, endSeconds - currentStart);
      } else if (currentDuration > 0) {
        // Remove HTML tags such as <c> or <v>
        const clean = line.replace(/<[^>]+>/g, '').trim();
        if (clean) {
          currentText = currentText ? `${currentText} ${clean}` : clean;
        }
      }
    }

    if (currentText && currentDuration > 0) {
      segments.push({
        start: currentStart,
        duration: currentDuration,
        text: currentText.trim(),
      });
    }

    return segments;
  }
}

export const transcriptService = new TranscriptService();
